Add support for Amazon Linux based images
toolbx-images/images pull request #54
Opened 2022-11-30 16:08 UTC by thimslugga

This is related to #47 and https://github.com/toolbx-images/images/pull/48

2022-12-05 12:59 UTC, travier commented on amazonlinux/2/README.md
> +[Toolbox](https://containertoolbx.org/) is a tool for Linux operating systems, which allows the use of containerized command line environments. It is built on top of [Podman](https://podman.io/) and
Let's remove this file. We don't include it in the other images.

2022-12-05 13:00 UTC, travier commented on amazonlinux/2/Containerfile
> +  name="$NAME" \
We're removing those variables from the image ENV. See https://github.com/toolbx-images/images/issues/50

2022-12-05 13:03 UTC, travier requested changes

2022-12-05 13:03 UTC, travier commented on amazonlinux/2/Containerfile
> +ENV NAME=amazonlinux-toolbox VERSION=2
We're removing those variables from the image ENV. See https://github.com/toolbx-images/images/issues/50

2022-12-05 13:03 UTC, travier commented on amazonlinux/2/Containerfile
> +COPY README.md packages extra-packages missing-docs /
```suggestion
COPY packages extra-packages missing-docs /
```

2022-12-05 13:03 UTC, travier commented on amazonlinux/2/justfile
> +# justfile
Let's not include this one either

2022-12-05 13:03 UTC, travier commented on amazonlinux/2022/Containerfile
> +ENV NAME=amazonlinux-toolbox VERSION=2022
idem

2022-12-05 13:03 UTC, travier commented on amazonlinux/2022/Containerfile
> +COPY README.md missing-docs extra-packages /
```suggestion
COPY missing-docs extra-packages /
```

2022-12-05 13:03 UTC, travier commented on amazonlinux/2022/justfile
> +# justfile
idem

2022-12-06 02:18 UTC, thimslugga commented on amazonlinux/2/Containerfile
> +ENV NAME=amazonlinux-toolbox VERSION=2
I've removed the ENV and replaced with the name and version

2022-12-06 02:19 UTC, thimslugga commented
> Thanks. This is also missing GitHub workflow config.

added

2022-12-13 19:08 UTC, travier approved these changes

2022-12-13 19:09 UTC, travier commented
Thanks! I'll invite you to the org as a maintainer.

2022-12-13 19:11 UTC, travier commented
Well, now you'll have to fix the containerfiles 🙂.

2023-02-01 16:50 UTC, closed without merging