alpine: Remove NAME and VERSION variables
toolbx-images/images pull request #59
Opened 2023-01-13 02:33 UTC by castrojo

As per recommendations in #50

2023-01-13 08:52 UTC, travier commented
You should remove the ENV vars but keep the labels

2023-01-16 10:16 UTC, travier commented
You need to move the names and version into the labels as we don't set the env now.

2023-01-22 19:50 UTC, castrojo commented
Wow that was embarrassing, ok PTAL.

2023-01-23 17:32 UTC, travier approved these changes

2023-01-23 17:33 UTC, travier requested changes

2023-01-23 17:33 UTC, travier commented on alpine/3.16/Containerfile
> +      com.redhat.component="alpine-toolbox" \
Hum, I think this only makes sense for RPM based images.

2023-01-23 17:34 UTC, travier commented
Sorry one last nit

2023-01-24 14:38 UTC, travier approved these changes

2023-01-24 14:38 UTC, merged